language: python
python:
  - 3.6
services:
  - docker

install:
  - docker-compose build
  - docker-compose up -d
  - pip install pytest requests

script:
  - docker-compose -p test run -p 8000 --rm web python manage.py test apps