language: python
python:
  - 3.6
services:
  - docker-compose

install:
  - docker-compose build
  - docker-compose up -d

script:
  - pytest /home/travis/build/tungtokyo1108/Gunosy-Data_Analysis/tests/test.py