version: '3.7'

services: 
    web:
        build: ./backend/server
        command: bash -c "python Gunosy_data_generate.py && python Gunosy_model_training.py && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - ./backend/server/:/backend/server/
        ports: 
            - 8000:8000
        env_file: 
            - ./.env.dev
        depends_on: 
            - db 
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django
            - POSTGRES_DB=hello_django_dev
volumes: 
    postgres_data:
