version: '3.7'

services: 
    web:
        build: ./backend/server
        command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
        volumes: 
            - ./backend/server/:/backend/server/
        ports: 
            - 8000:8000
        env_file: 
            - ./.env.dev